name: Compile CyberKit for iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Select the correct Xcode tool
      run: |
        sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

    - name: Instal required dependencies & Theos
      run: |
        export THEOS=/Users/runner/theos
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
        echo "THEOS=$THEOS" >> $GITHUB_ENV

    - name: Execute CyberKit configure script
      run: |
        ./configure

    - name: Compile (arm64)
      run: |
        xcodebuild -project Source/WebKit/WebKit.xcodeproj \
                   -scheme WebKit \
                   -configuration Release \
                   -sdk iphoneos \
                   ARCHS="arm64" \
                   DEPLOYMENT_TARGET=15.0 \
                   ONLY_ACTIVE_ARCH=NO \
                   -derivedDataPath build

    - name: Up the compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: CyberKit-WebKit-iOS15-arm64
        path: build_output/Build/Products/Release-iphoneos/
